services:
  app:
    image: mysociety/parl-motion-detector:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspaces/parl_motion_detector      
    volumes:
      - ./:/workspaces/parl_motion_detector/