name: Run meta pytest suite on repo

on:
  pull_request:
  push:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      # checkout the meta template repo that is a cookiecutter/auto-repo
      - uses: actions/checkout@v3
        with:
          repository: mysociety/python-data-auto-template
          path: template
          fetch-depth: 0

      - name: delete current template
        shell: bash
        run: |
          rm -r "template/{{ cookiecutter.repo_name }}"

      # checkout the latest version of the template-data-repo template
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          path: "template/{{ cookiecutter.repo_name }}"

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Setup required packages
        run: |
          pip install pytest cookiecutter poetry

      # run pytest, but with the UPDATE_TO_LATEST flag off. 
      - name: run pytest
        run: |
          mv template /tmp/template
          cd /tmp/template
          python -m pytest
        shell: bash
        env:
          UPDATE_TO_LATEST: False
